version: '2'
services:
  redis-node-0:
    image: 59.125.100.235:5000/hitrustai/redis-cluster-redisgraph:6.2.10
    ports:
      - 7001:7001
      - 17001:17001
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
      - ./etc/redis-c0/redis.conf:/opt/bitnami/redis/etc/redis.conf
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.10.112'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_PORT_NUMBER=7001'
      - 'REDIS_PASSWORD=pass.123'
      - 'REDIS_NODES=192.168.10.112:7001 192.168.10.112:7002 192.168.10.112:7003 192.168.10.112:7004 192.168.10.112:7005 192.168.10.112:7006'

  redis-node-1:
    image: 59.125.100.235:5000/hitrustai/redis-cluster-redisgraph:6.2.10
    ports:
      - 7002:7002
      - 17002:17002
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
      - ./etc/redis-c1/redis.conf:/opt/bitnami/redis/etc/redis.conf
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.10.112'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_PORT_NUMBER=7002'
      - 'REDIS_PASSWORD=pass.123'
      - 'REDIS_NODES=192.168.10.112:7001 192.168.10.112:7002 192.168.10.112:7003 192.168.10.112:7004 192.168.10.112:7005 192.168.10.112:7006'

  redis-node-2:
    image: 59.125.100.235:5000/hitrustai/redis-cluster-redisgraph:6.2.10
    ports:
      - 7003:7003
      - 17003:17003
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
      - ./etc/redis-c2/redis.conf:/opt/bitnami/redis/etc/redis.conf
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.10.112'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_PORT_NUMBER=7003'
      - 'REDIS_PASSWORD=pass.123'
      - 'REDIS_NODES=192.168.10.112:7001 192.168.10.112:7002 192.168.10.112:7003 192.168.10.112:7004 192.168.10.112:7005 192.168.10.112:7006'

  redis-node-3:
    image: 59.125.100.235:5000/hitrustai/redis-cluster-redisgraph:6.2.10
    ports:
      - 7004:7004
      - 17004:17004
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
      - ./etc/redis-c3/redis.conf:/opt/bitnami/redis/etc/redis.conf
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.10.112'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_PORT_NUMBER=7004'
      - 'REDIS_PASSWORD=pass.123'
      - 'REDIS_NODES=192.168.10.112:7001 192.168.10.112:7002 192.168.10.112:7003 192.168.10.112:7004 192.168.10.112:7005 192.168.10.112:7006'

  redis-node-4:
    image: 59.125.100.235:5000/hitrustai/redis-cluster-redisgraph:6.2.10
    ports:
      - 7005:7005
      - 17005:17005
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
      - ./etc/redis-c4/redis.conf:/opt/bitnami/redis/etc/redis.conf
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.10.112'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_PORT_NUMBER=7005'
      - 'REDIS_PASSWORD=pass.123'
      - 'REDIS_NODES=192.168.10.112:7001 192.168.10.112:7002 192.168.10.112:7003 192.168.10.112:7004 192.168.10.112:7005 192.168.10.112:7006'

  redis-node-5:
    image: 59.125.100.235:5000/hitrustai/redis-cluster-redisgraph:6.2.10
    ports:
      - 7006:7006
      - 17006:17006
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
      - ./etc/redis-c5/redis.conf:/opt/bitnami/redis/etc/redis.conf
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.10.112'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_PORT_NUMBER=7006'
      - 'REDIS_PASSWORD=pass.123'
      - 'REDISCLI_AUTH=pass.123'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=192.168.10.112:7001 192.168.10.112:7002 192.168.10.112:7003 192.168.10.112:7004 192.168.10.112:7005 192.168.10.112:7006'
      - 'REDIS_CLUSTER_CREATOR=no'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local

# redis-cli --cluster create 192.168.10.112:7001 192.168.10.112:7002 192.168.10.112:7003 192.168.10.112:7004 192.168.10.112:7005 192.168.10.112:7006 --cluster-replicas 1 -a pass.123